spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/h2mysqldb?useSSL=false&serverTimezone=UTC
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect:
        hibernate: org.hibernate.dialect.MySQL8Dialect
info:
  project:
    env: local
server:
  port: '8084'